from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class SubTask(BaseModel):
    task_id: str = Field(..., description="Unique subtask identifier, e.g. TASK-1")
    description: str = Field(..., description="Detailed description of subtask objective")
    category: str = Field(..., description="Subtask category: general, coding, reasoning, mathematics, explanation, factual, summarization")
    assigned_model: str = Field(..., description="Production model selected by BaselineAdaptivePolicy")
    dependencies: List[str] = Field(default_factory=list, description="List of prerequisite subtask IDs")
    
    # Task Lifecycle & Routing Detail Fields
    status: str = Field("PENDING", description="Task execution state: PENDING, READY, RUNNING, COMPLETED, FAILED, BLOCKED, CANCELLED")
    provider: Optional[str] = Field(None, description="Provider executing the task, e.g. Local Ollama, Groq API, Google Gemini API")
    actual_model: Optional[str] = Field(None, description="Model that actually produced the successful response")
    actual_provider: Optional[str] = Field(None, description="Provider that actually produced the successful response")
    rl_shadow_model: Optional[str] = Field(None, description="Shadow model recommendation from RLContextualBanditPolicy")
    rl_agreement: Optional[bool] = Field(None, description="True if BaselineAdaptivePolicy and RL shadow recommendation match")
    rl_predicted_q_value: Optional[float] = Field(None, description="Predicted Q-value from RL Contextual Bandit policy for chosen action")
    generated_text: Optional[str] = Field(None, description="Output text generated by the assigned model for this subtask")
    execution_success: bool = Field(False, description="True if subtask execution completed successfully")
    latency_ms: float = Field(0.0, description="Latency in milliseconds for subtask execution")
    error_message: Optional[str] = Field(None, description="Error details if subtask execution failed")

    # Subtask Cost Telemetry Fields
    cost: float = Field(0.0, description="Calculated monetary API execution cost in USD")
    cost_currency: str = Field("USD", description="Currency code (default USD)")
    cost_source: str = Field("zero_local", description="Source: zero_local, configured_pricing_estimate, provider_reported, unknown")
    input_tokens: int = Field(0, description="Prompt tokens reported by the successful provider response")
    output_tokens: int = Field(0, description="Completion tokens reported by the successful provider response")
    total_tokens: int = Field(0, description="Total tokens reported by the successful provider response")
    
    # Failover Telemetry & Prompt Integrity Fields
    initial_model: Optional[str] = Field(None, description="Initial model selected by BaselineAdaptivePolicy prior to failover")
    failover_used: bool = Field(False, description="True if fallback model was executed following primary provider failure")
    attempts: int = Field(1, description="Total execution attempts for this subtask")
    attempts_detail: List[Dict[str, Any]] = Field(default_factory=list, description="Per-attempt telemetry breakdown (model, provider, status, error, latency)")

    # Immutable Task Spec & Validation Fields
    original_user_prompt: Optional[str] = Field(None, description="Original overall user prompt passed to the orchestration pipeline")
    task_objective: Optional[str] = Field(None, description="Immutable normalized task objective text")
    domain_context: Optional[str] = Field(None, description="Extracted domain context keywords from original user prompt")
    prompt_hash: Optional[str] = Field(None, description="Deterministic SHA-256 hash of task_id, original_user_prompt, and task_objective")
    max_output_tokens: Optional[int] = Field(None, description="Max output token budget based on subtask complexity")
    relevance_score: Optional[float] = Field(None, description="Semantic relevance score of generated text vs task objective")
    validation_status: Optional[str] = Field("unverified", description="Validation state: passed, failed, or unverified")

class ComplexTaskPlan(BaseModel):
    is_complex: bool = Field(True, description="True if prompt was classified as a complex task requiring decomposition")
    original_prompt: str = Field(..., description="Original complex user prompt")
    subtasks: List[SubTask] = Field(..., description="List of decomposed subtasks with model allocations and dependencies")
    execution_levels: List[List[str]] = Field(..., description="Ordered parallel execution groups (levels of independent subtasks)")
    total_subtasks: int = Field(..., description="Total count of decomposed subtasks")
    plan_latency_ms: float = Field(..., description="Decomposition and task plan generation latency in milliseconds")
    aggregated_response: Optional[str] = Field(None, description="Final aggregated response synthesized from completed subtasks")
    execution_success: bool = Field(False, description="True if complex task execution completed successfully")
    total_execution_latency_ms: float = Field(0.0, description="Total latency for end-to-end complex task execution in milliseconds")

    # Workflow Cost Aggregation Fields
    total_workflow_cost: float = Field(0.0, description="Sum of all actual provider execution costs + synthesis cost in USD")
    synthesis_cost: float = Field(0.0, description="LLM synthesis cost (0.0 for S2 deterministic assembly)")
    cost_currency: str = Field("USD", description="Currency code (default USD)")
    cost_source: str = Field("zero_local", description="Zero-local, configured-pricing estimate, or unknown")
    total_input_tokens: int = Field(0, description="Total prompt tokens across billable provider calls")
    total_output_tokens: int = Field(0, description="Total completion tokens across billable provider calls")
    total_tokens: int = Field(0, description="Total tokens across billable provider calls")
    calls: List[Dict[str, Any]] = Field(default_factory=list, description="Per-call normalized cost/usage records for workflow aggregation")

    # Canonical actual-execution summary derived from provider records.
    actual_models: List[str] = Field(default_factory=list)
    actual_providers: List[str] = Field(default_factory=list)
    successful_models: List[str] = Field(default_factory=list)
    successful_providers: List[str] = Field(default_factory=list)
    final_model: Optional[str] = Field(None)
    final_provider: Optional[str] = Field(None)
    failover_used: bool = Field(False)
    local_cost: float = Field(0.0)
    cloud_cost: float = Field(0.0)
    local_calls: int = Field(0)
    cloud_calls: int = Field(0)
    billable_calls: int = Field(0)
    baseline_fallback: bool = Field(False)

class ComplexPlanRequest(BaseModel):
    prompt: str = Field(..., description="Complex user prompt to decompose into a task allocation plan")
    execution_mode: Optional[str] = Field("local", description="Execution mode: local or online")
    primary_selected_model: Optional[str] = Field(None, description="Authoritative policy selected model from BaselineAdaptivePolicy")
